# Generated by Django 4.1.7 on 2023-03-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_posts_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="project",
        ),
    ]
